name: Test

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: mydatabase
                ports:
                    - 5432:5432
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              env:
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/mydatabase'
                  SHADOW_DATABASE_URL: ''
                  PORT: '5000'
                  JWT_SECRET: 'secret'

                  AWS_ACCESS_KEY: 'AKIAXRJYITJVGJ7STP4J'
                  AWS_SECRET_KEY: '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'
              run: npm test
